### ISSUE TITLE
feat(api): add POST /users/authenticate

### ISSUE THREAD

**Issue by serialLinker** [serialLinker/admin-boxe#2]
I need to create an api http resource (POST /users/authenticate)
I need a json object like this :

{
 "username" : "my-email@fake-email.com",
 "password" : "myBeautifulPassword"
}
The api will return a token jwt into a field "token" like this :

{
   "token" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE1NzE5Mzk1MTQsImV4cCI6MTYwMzQ3NTUxNCwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsImVtYWlsIjoiZmFrZUVtYWlsQHRlc3QuY29tIiwiZmlyc3ROYW1lIjoiSm9obiIsImxhc3ROYW1lIjoiRG9lIiwicm9sZXMiOlsiUk9MRV9GSUdIVEVSIiwiUk9MRV9BRE1JTiJdfQ.1BR8YxK35MtCm5pbgCTTV8ZUcW-jmW766ANNxxocyko" 
}
This token contains that fields (at least) :

"email": "fakeEmail@test.com",
"firstName": "John",
"lastName": "Doe",
"roles": [
 "ROLE_FIGHTER",
 "ROLE_ADMIN"
]

NB : In a first time the password encryption is not required

**Comment by jabbar86** [comment]
what you want to do can you be more specific ?

**Comment by ValentinBouffard** [comment]
I'm doing it.

**Comment by serialLinker** [comment]
Hi, 

I need a new resource POST /users/authenticate, with in body 
`{
"username" : "my-email@fake-email.com",
"password" : "myBeautifulPassword"
}`

next you user User.java to find the user an build a JWT token based on his profile
